name: Daily Update with RSS

on:
  schedule:
    - cron: '20 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python rizospastis.py

     - name: Generate RSS Feed
        run: |
          DATE=$(date -R)
          REPO_URL="https://raw.githubusercontent.com/${{ github.repository }}/main"
          # Υπολογισμός μεγέθους αρχείου (το απαιτεί το enclosure)
          FILE_SIZE=$(stat -c%s "rizospastis_current.pdf")
          
          cat <<EOF > rss.xml
          <?xml version="1.0" encoding="UTF-8" ?>
          <rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
          <channel>
            <title>Rizospastis Daily PDF</title>
            <link>${REPO_URL}/rizospastis_current.pdf</link>
            <description>Απευθείας λήψη του σημερινού Ριζοσπάστη</description>
            <language>el</language>
            <lastBuildDate>${DATE}</lastBuildDate>
            <item>
              <title>Ριζοσπάστης - $(date +'%d/%m/%Y')</title>
              <link>${REPO_URL}/rizospastis_current.pdf</link>
              <description>Κάντε κλικ για λήψη της εφημερίδας σε μορφή PDF.</description>
              <guid isPermaLink="false">rizospastis-$(date +'%Y-%m-%d')</guid>
              <pubDate>${DATE}</pubDate>
              <enclosure url="${REPO_URL}/rizospastis_current.pdf" length="${FILE_SIZE}" type="application/pdf" />
            </item>
          </channel>
          </rss>
          EOF

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add rizospastis_current.pdf rss.xml
          git commit -m "Update PDF and RSS for $(date +'%Y-%m-%d')" || exit 0
          git push
