name: Push Rizospastis to Dropbox

on:
  schedule:
    - cron: '20 5 * * *'  # 08:20 ώρα Ελλάδας
  workflow_dispatch:      # Για να το τρέχεις χειροκίνητα

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script and Upload
        env:
          DBX_APP_KEY: ${{ secrets.DBX_APP_KEY }}
          DBX_APP_SECRET: ${{ secrets.DBX_APP_SECRET }}
          DBX_REFRESH_TOKEN: ${{ secrets.DBX_REFRESH_TOKEN }}
        run: python rizospastis.py
